# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstGUIAgain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 200)
        MainWindow.setMinimumSize(QtCore.QSize(468, 200))
        MainWindow.setMaximumSize(QtCore.QSize(468, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PlusForFirst = QtWidgets.QPushButton(self.centralwidget)
        self.PlusForFirst.setGeometry(QtCore.QRect(68, 80, 54, 42))
        self.PlusForFirst.setStyleSheet("\n"
"background-color: rgb(67, 136, 11);")
        self.PlusForFirst.setObjectName("PlusForFirst")
        self.MinusForFirst = QtWidgets.QPushButton(self.centralwidget)
        self.MinusForFirst.setGeometry(QtCore.QRect(118, 80, 52, 41))
        self.MinusForFirst.setStyleSheet("background-color: rgb(189, 0, 0);\n"
"")
        self.MinusForFirst.setObjectName("MinusForFirst")
        self.PlusForSecond = QtWidgets.QPushButton(self.centralwidget)
        self.PlusForSecond.setGeometry(QtCore.QRect(168, 80, 52, 41))
        self.PlusForSecond.setStyleSheet("\n"
"background-color: rgb(67, 136, 11);")
        self.PlusForSecond.setObjectName("PlusForSecond")
        self.MinusForSecond = QtWidgets.QPushButton(self.centralwidget)
        self.MinusForSecond.setGeometry(QtCore.QRect(218, 80, 52, 41))
        self.MinusForSecond.setStyleSheet("background-color: rgb(189, 0, 0);\n"
"")
        self.MinusForSecond.setObjectName("MinusForSecond")
        self.PlusForThird = QtWidgets.QPushButton(self.centralwidget)
        self.PlusForThird.setGeometry(QtCore.QRect(268, 80, 52, 41))
        self.PlusForThird.setStyleSheet("\n"
"background-color: rgb(67, 136, 11);")
        self.PlusForThird.setObjectName("PlusForThird")
        self.MinusForThird = QtWidgets.QPushButton(self.centralwidget)
        self.MinusForThird.setGeometry(QtCore.QRect(318, 80, 52, 41))
        self.MinusForThird.setStyleSheet("background-color: rgb(189, 0, 0);\n"
"")
        self.MinusForThird.setObjectName("MinusForThird")
        self.PlusForFourth = QtWidgets.QPushButton(self.centralwidget)
        self.PlusForFourth.setGeometry(QtCore.QRect(368, 80, 52, 41))
        self.PlusForFourth.setStyleSheet("\n"
"background-color: rgb(67, 136, 11);")
        self.PlusForFourth.setObjectName("PlusForFourth")
        self.NextQ = QtWidgets.QPushButton(self.centralwidget)
        self.NextQ.setGeometry(QtCore.QRect(0, 120, 471, 41))
        self.NextQ.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.NextQ.setObjectName("NextQ")
        self.PreviousQ = QtWidgets.QPushButton(self.centralwidget)
        self.PreviousQ.setGeometry(QtCore.QRect(0, 160, 471, 41))
        self.PreviousQ.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.PreviousQ.setObjectName("PreviousQ")
        self.MinusForFourth = QtWidgets.QPushButton(self.centralwidget)
        self.MinusForFourth.setGeometry(QtCore.QRect(418, 80, 52, 41))
        self.MinusForFourth.setStyleSheet("background-color: rgb(189, 0, 0);\n"
"")
        self.MinusForFourth.setObjectName("MinusForFourth")
        self.Players = QtWidgets.QLabel(self.centralwidget)
        self.Players.setGeometry(QtCore.QRect(0, 0, 471, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Players.setFont(font)
        self.Players.setObjectName("Players")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 41, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(58, -40, 20, 170))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(158, -30, 20, 170))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(258, -20, 20, 170))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 71, 481, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(358, -20, 20, 170))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Sigma = QtWidgets.QLabel(self.centralwidget)
        self.Sigma.setGeometry(QtCore.QRect(0, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Sigma.setFont(font)
        self.Sigma.setObjectName("Sigma")
        self.Sum1 = QtWidgets.QLabel(self.centralwidget)
        self.Sum1.setGeometry(QtCore.QRect(70, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sum1.setFont(font)
        self.Sum1.setObjectName("Sum1")
        self.Sum2 = QtWidgets.QLabel(self.centralwidget)
        self.Sum2.setGeometry(QtCore.QRect(170, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sum2.setFont(font)
        self.Sum2.setObjectName("Sum2")
        self.Sum3 = QtWidgets.QLabel(self.centralwidget)
        self.Sum3.setGeometry(QtCore.QRect(270, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sum3.setFont(font)
        self.Sum3.setObjectName("Sum3")
        self.Sum4 = QtWidgets.QLabel(self.centralwidget)
        self.Sum4.setGeometry(QtCore.QRect(370, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sum4.setFont(font)
        self.Sum4.setObjectName("Sum4")
        self.line_7.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.PlusForFirst.raise_()
        self.line_4.raise_()
        self.MinusForFirst.raise_()
        self.PlusForSecond.raise_()
        self.MinusForSecond.raise_()
        self.PlusForThird.raise_()
        self.MinusForThird.raise_()
        self.MinusForFourth.raise_()
        self.PlusForFourth.raise_()
        self.NextQ.raise_()
        self.PreviousQ.raise_()
        self.Players.raise_()
        self.line.raise_()
        self.line_5.raise_()
        self.Sigma.raise_()
        self.Sum1.raise_()
        self.Sum2.raise_()
        self.Sum3.raise_()
        self.Sum4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.number=1

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор для Своей Игры"))
        self.PlusForFirst.setText(_translate("MainWindow", "+"+str(10* self.number)))
        self.MinusForFirst.setText(_translate("MainWindow", "-"+str(10* self.number)))
        self.PlusForSecond.setText(_translate("MainWindow", "+"+str(10* self.number)))
        self.MinusForSecond.setText(_translate("MainWindow", "-"+str(10* self.number)))
        self.PlusForThird.setText(_translate("MainWindow", "+"+str(10* self.number)))
        self.MinusForThird.setText(_translate("MainWindow", "-"+str(10* self.number)))
        self.PlusForFourth.setText(_translate("MainWindow", "+"+str(10* self.number)))
        self.NextQ.setText(_translate("MainWindow", "Следующий вопрос"))
        self.PreviousQ.setText(_translate("MainWindow", "Предыдущий вопрос"))
        self.MinusForFourth.setText(_translate("MainWindow", "-"+str(10* self.number)))
        self.Players.setText(_translate("MainWindow", "  Игрок №                   1                                2                               3                               4                      "))
        self.Sigma.setText(_translate("MainWindow", "   Σ"))
        self.Sum1.setText(_translate("MainWindow", "0"))
        self.Sum2.setText(_translate("MainWindow", "     0"))
        self.Sum3.setText(_translate("MainWindow", "     0"))
        self.Sum4.setText(_translate("MainWindow", "     0"))
    def add_functions(self):
        self.PlusForFirst.clicked.connect(self.plus1)
        self.MinusForFirst.clicked.connect(self.minus1)
        self.PlusForSecond.clicked.connect(self.plus2)
        self.MinusForSecond.clicked.connect(self.minus2)
        self.PlusForThird.clicked.connect(self.plus3)
        self.MinusForThird.clicked.connect(self.minus3)
        self.PlusForFourth.clicked.connect(self.plus4)
        self.MinusForFourth.clicked.connect(self.minus4)
        self.NextQ.clicked.connect(self.Next)
        self.PreviousQ.clicked.connect(self.Previous)
    def plus1(self):
        self.Sum1.setText(str(int(self.Sum1.text())+ self.number*10))
    def minus1(self):
        self.Sum1.setText(str(int(self.Sum1.text())- self.number*10))
    def plus2(self):
        self.Sum2.setText(str(int(self.Sum2.text())+ self.number*10))
    def minus2(self):
        self.Sum2.setText(str(int(self.Sum2.text())- self.number*10))
    def plus3(self):
        self.Sum3.setText(str(int(self.Sum3.text())+ self.number*10))
    def minus3(self):
        self.Sum3.setText(str(int(self.Sum3.text())- self.number*10))
    def plus4(self):
        self.Sum4.setText(str(int(self.Sum4.text())+ self.number*10))
    def minus4(self):
        self.Sum4.setText(str(int(self.Sum4.text())- self.number*10))
    def Next(self):          
        if self.number ==5:
        
            self.PlusForFirst.setText("+"+str(int(self.PlusForFirst.text())-50))
            self.PlusForSecond.setText("+"+str(int(self.PlusForSecond.text())-50))
            self.PlusForThird.setText("+"+str(int(self.PlusForThird.text())-50))
            self.PlusForFourth.setText("+"+str(int(self.PlusForFourth.text())-50))
            self.MinusForFirst.setText("-"+str(-1*int(self.MinusForFirst.text())-50))
            self.MinusForSecond.setText("-"+str(-1*int(self.MinusForSecond.text())-50))
            self.MinusForThird.setText("-"+str(-1*int(self.MinusForThird.text())-50))
            self.MinusForFourth.setText("-"+str(-1*int(self.MinusForFourth.text())-50))
            self.number=0
            
        self.PlusForFirst.setText("+"+str(int(self.PlusForFirst.text())+10))
        self.PlusForSecond.setText("+"+str(int(self.PlusForSecond.text())+10))
        self.PlusForThird.setText("+"+str(int(self.PlusForThird.text())+10))
        self.PlusForFourth.setText("+"+str(int(self.PlusForFourth.text())+10))
        self.MinusForFirst.setText("-"+str(-1*int(self.MinusForFirst.text())+10))
        self.MinusForSecond.setText("-"+str(-1*int(self.MinusForSecond.text())+10))
        self.MinusForThird.setText("-"+str(-1*int(self.MinusForThird.text())+10))
        self.MinusForFourth.setText("-"+str(-1*int(self.MinusForFourth.text())+10))
        self.number+= 1
    def Previous(self):
        if self.number ==1:
        
            self.PlusForFirst.setText("+"+str(int(self.PlusForFirst.text())+50))
            self.PlusForSecond.setText("+"+str(int(self.PlusForSecond.text())+50))
            self.PlusForThird.setText("+"+str(int(self.PlusForThird.text())+50))
            self.PlusForFourth.setText("+"+str(int(self.PlusForFourth.text())+50))
            self.MinusForFirst.setText("-"+str(-1*int(self.MinusForFirst.text())+50))
            self.MinusForSecond.setText("-"+str(-1*int(self.MinusForSecond.text())+50))
            self.MinusForThird.setText("-"+str(-1*int(self.MinusForThird.text())+50))
            self.MinusForFourth.setText("-"+str(-1*int(self.MinusForFourth.text())+50))
            self.number=6
            
        self.PlusForFirst.setText("+"+str(int(self.PlusForFirst.text())-10))
        self.PlusForSecond.setText("+"+str(int(self.PlusForSecond.text())-10))
        self.PlusForThird.setText("+"+str(int(self.PlusForThird.text())-10))
        self.PlusForFourth.setText("+"+str(int(self.PlusForFourth.text())-10))
        self.MinusForFirst.setText("-"+str(-1*int(self.MinusForFirst.text())-10))
        self.MinusForSecond.setText("-"+str(-1*int(self.MinusForSecond.text())-10))
        self.MinusForThird.setText("-"+str(-1*int(self.MinusForThird.text())-10))
        self.MinusForFourth.setText("-"+str(-1*int(self.MinusForFourth.text())-10))
        self.number-= 1
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
